### ISSUE TITLE
remote control?

### ISSUE THREAD

**Issue by deusyv** [kfricke/micropython-sonoff-switch#2]
Hello, can we send MQTT commands to the sonoff module from another client module esp 8266 (remote control). What part of the code handles this action.

**Comment by kfricke** [comment]
The pushbutton does implement this already. It does not switch the relay directly, but instead does publish the switched state onto the MQTT broker. There the code itself is subscribed to receive the state switch command indirectly from the pushbutton.
https://github.com/kfricke/micropython-sonoff-switch/blob/master/sonoff_switch.py#L74

This line does show you the MQTT publish command. It is embedded in a callback methd for the used scheduling framework, but can easily be seen as a standalone command.
Please also be aware of the fact that the communication is always done via the MQTT broker and not directly between your remote and the switch!

**Comment by deusyv** [comment]
Thank you!

2017-04-13 0:43 GMT+02:00 kfricke <notifications@github.com>:
